package zzjz.mapper;

import org.apache.ibatis.annotations.Param;
import zzjz.bean.Attendance;
import zzjz.bean.AttendanceExcel;
import zzjz.bean.AttendanceRequest;

import java.util.List;

/**
 * @author 彭鹏
 * @ClassName: AttendanceMapper
 * @Description:
 * @date 2017年04月12日15:15
 */
public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Attendance key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    Attendance selectByPrimaryKey(Attendance key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attendance record);

    int addAttendanceList(@Param("res") List<AttendanceExcel> res);

    List<Attendance> getAttendancePageList(AttendanceRequest request);
}
