package zzjz.mapper;

import zzjz.bean.Trip;
import zzjz.bean.TripRequest;

import java.util.List;

/**
 * @author 彭鹏
 * @ClassName: TripMapper
 * @Description:
 * @date 2017年04月13日11:14
 */
public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    int insertSelective(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trip record);

    /**
     * 分页获取出差列表信息
     * @param trip
     * @return 出差列表
     */
    List<Trip> getTripList(TripRequest trip);

    int deleteSelective(Trip trip);
}
