package zzjz.mapper;

import zzjz.bean.VacationDetail;

public interface VacationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vacation_detail
     *
     * @mbggenerated
     */
    int insert(VacationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vacation_detail
     *
     * @mbggenerated
     */
    int insertSelective(VacationDetail record);

    int deleteById(Integer id);
}