package zzjz.bean;

import org.jeecgframework.poi.excel.annotation.Excel;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class AttendanceExcel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.user_id
     *
     * @mbggenerated
     */
    @Excel( name = "考勤号码" )
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.check_date
     *
     * @mbggenerated
     */
    @Excel( name = "日期" ,importFormat="yyyy-MM-dd")
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.user_name
     *
     * @mbggenerated
     */
    @Excel( name = "姓名" )
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.begin_time
     *
     * @mbggenerated
     */
    @Excel( name = "上班时间" ,importFormat="HH:mm")
    private String beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.end_time
     *
     * @mbggenerated
     */
    @Excel( name = "下班时间" ,importFormat="HH:mm")
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.sign_time
     *
     * @mbggenerated
     */
    @Excel( name = "签到时间" ,importFormat="HH:mm")
    private String signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.leave_time
     *
     * @mbggenerated
     */
    @Excel( name = "签退时间" ,importFormat="HH:mm")
    private String leaveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.depart
     *
     * @mbggenerated
     */
    @Excel( name = "部门" )
    private String depart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.all_day
     *
     * @mbggenerated
     */
    private String allDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.mor_day
     *
     * @mbggenerated
     */
    private String morDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.aft_day
     *
     * @mbggenerated
     */
    private String aftDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.eve_day
     *
     * @mbggenerated
     */
    private String eveDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.is_error
     *
     * @mbggenerated
     */
    private String isError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.error_desc
     *
     * @mbggenerated
     */
    private String errorDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.late
     *
     * @mbggenerated
     */
    private Double late;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.early
     *
     * @mbggenerated
     */
    private Double early;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.absent
     *
     * @mbggenerated
     */
    private Double absent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.over_time
     *
     * @mbggenerated
     */
    private Double overTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attendance.work_day
     *
     * @mbggenerated
     */
    private String workDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.user_id
     *
     * @return the value of tb_attendance.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.user_id
     *
     * @param userId the value for tb_attendance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.check_date
     *
     * @return the value of tb_attendance.check_date
     *
     * @mbggenerated
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.check_date
     *
     * @param checkDate the value for tb_attendance.check_date
     *
     * @mbggenerated
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate == null ? null : checkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.user_name
     *
     * @return the value of tb_attendance.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.user_name
     *
     * @param userName the value for tb_attendance.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.begin_time
     *
     * @return the value of tb_attendance.begin_time
     *
     * @mbggenerated
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.begin_time
     *
     * @param beginTime the value for tb_attendance.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.end_time
     *
     * @return the value of tb_attendance.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.end_time
     *
     * @param endTime the value for tb_attendance.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.sign_time
     *
     * @return the value of tb_attendance.sign_time
     *
     * @mbggenerated
     */
    public String getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.sign_time
     *
     * @param signTime the value for tb_attendance.sign_time
     *
     * @mbggenerated
     */
    public void setSignTime(String signTime) {
        this.signTime = signTime == null ? null : signTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.leave_time
     *
     * @return the value of tb_attendance.leave_time
     *
     * @mbggenerated
     */
    public String getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.leave_time
     *
     * @param leaveTime the value for tb_attendance.leave_time
     *
     * @mbggenerated
     */
    public void setLeaveTime(String leaveTime) {
        this.leaveTime = leaveTime == null ? null : leaveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.depart
     *
     * @return the value of tb_attendance.depart
     *
     * @mbggenerated
     */
    public String getDepart() {
        return depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.depart
     *
     * @param depart the value for tb_attendance.depart
     *
     * @mbggenerated
     */
    public void setDepart(String depart) {
        this.depart = depart == null ? null : depart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.all_day
     *
     * @return the value of tb_attendance.all_day
     *
     * @mbggenerated
     */
    public String getAllDay() {
        return allDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.all_day
     *
     * @param allDay the value for tb_attendance.all_day
     *
     * @mbggenerated
     */
    public void setAllDay(String allDay) {
        this.allDay = allDay == null ? null : allDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.mor_day
     *
     * @return the value of tb_attendance.mor_day
     *
     * @mbggenerated
     */
    public String getMorDay() {
        return morDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.mor_day
     *
     * @param morDay the value for tb_attendance.mor_day
     *
     * @mbggenerated
     */
    public void setMorDay(String morDay) {
        this.morDay = morDay == null ? null : morDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.aft_day
     *
     * @return the value of tb_attendance.aft_day
     *
     * @mbggenerated
     */
    public String getAftDay() {
        return aftDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.aft_day
     *
     * @param aftDay the value for tb_attendance.aft_day
     *
     * @mbggenerated
     */
    public void setAftDay(String aftDay) {
        this.aftDay = aftDay == null ? null : aftDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.eve_day
     *
     * @return the value of tb_attendance.eve_day
     *
     * @mbggenerated
     */
    public String getEveDay() {
        return eveDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.eve_day
     *
     * @param eveDay the value for tb_attendance.eve_day
     *
     * @mbggenerated
     */
    public void setEveDay(String eveDay) {
        this.eveDay = eveDay == null ? null : eveDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.is_error
     *
     * @return the value of tb_attendance.is_error
     *
     * @mbggenerated
     */
    public String getIsError() {
        return isError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.is_error
     *
     * @param isError the value for tb_attendance.is_error
     *
     * @mbggenerated
     */
    public void setIsError(String isError) {
        this.isError = isError == null ? null : isError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.error_desc
     *
     * @return the value of tb_attendance.error_desc
     *
     * @mbggenerated
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.error_desc
     *
     * @param errorDesc the value for tb_attendance.error_desc
     *
     * @mbggenerated
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc == null ? null : errorDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.late
     *
     * @return the value of tb_attendance.late
     *
     * @mbggenerated
     */
    public Double getLate() {
        return late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.late
     *
     * @param late the value for tb_attendance.late
     *
     * @mbggenerated
     */
    public void setLate(Double late) {
        this.late = late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.early
     *
     * @return the value of tb_attendance.early
     *
     * @mbggenerated
     */
    public Double getEarly() {
        return early;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.early
     *
     * @param early the value for tb_attendance.early
     *
     * @mbggenerated
     */
    public void setEarly(Double early) {
        this.early = early;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.absent
     *
     * @return the value of tb_attendance.absent
     *
     * @mbggenerated
     */
    public Double getAbsent() {
        return absent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.absent
     *
     * @param absent the value for tb_attendance.absent
     *
     * @mbggenerated
     */
    public void setAbsent(Double absent) {
        this.absent = absent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attendance.over_time
     *
     * @return the value of tb_attendance.over_time
     *
     * @mbggenerated
     */
    public Double getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attendance.over_time
     *
     * @param overTime the value for tb_attendance.over_time
     *
     * @mbggenerated
     */
    public void setOverTime(Double overTime) {
        this.overTime = overTime;
    }

    public String getWorkDay() {
        return workDay;
    }

    public void setWorkDay(String workDay) {
        this.workDay = workDay;
    }
}