package zzjz.bean;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Column {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_column.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_column.column_sign
     *
     * @mbggenerated
     */
    private String columnSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_column.column_name
     *
     * @mbggenerated
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_column.is_show
     *
     * @mbggenerated
     */
    private Integer isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_column.id
     *
     * @return the value of tb_column.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_column.id
     *
     * @param id the value for tb_column.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_column.column_sign
     *
     * @return the value of tb_column.column_sign
     *
     * @mbggenerated
     */
    public String getColumnSign() {
        return columnSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_column.column_sign
     *
     * @param columnSign the value for tb_column.column_sign
     *
     * @mbggenerated
     */
    public void setColumnSign(String columnSign) {
        this.columnSign = columnSign == null ? null : columnSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_column.column_name
     *
     * @return the value of tb_column.column_name
     *
     * @mbggenerated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_column.column_name
     *
     * @param columnName the value for tb_column.column_name
     *
     * @mbggenerated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_column.is_show
     *
     * @return the value of tb_column.is_show
     *
     * @mbggenerated
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_column.is_show
     *
     * @param isShow the value for tb_column.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }
}