package zzjz.bean;

import java.util.Date;

public class Depart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.depart_id
     *
     * @mbggenerated
     */
    private Long departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.depart_name
     *
     * @mbggenerated
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.parent_depart
     *
     * @mbggenerated
     */
    private Long parentDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.id
     *
     * @return the value of tb_depart.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.id
     *
     * @param id the value for tb_depart.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.depart_id
     *
     * @return the value of tb_depart.depart_id
     *
     * @mbggenerated
     */
    public Long getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.depart_id
     *
     * @param departId the value for tb_depart.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(Long departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.depart_name
     *
     * @return the value of tb_depart.depart_name
     *
     * @mbggenerated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.depart_name
     *
     * @param departName the value for tb_depart.depart_name
     *
     * @mbggenerated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.level
     *
     * @return the value of tb_depart.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.level
     *
     * @param level the value for tb_depart.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.parent_depart
     *
     * @return the value of tb_depart.parent_depart
     *
     * @mbggenerated
     */
    public Long getParentDepart() {
        return parentDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.parent_depart
     *
     * @param parentDepart the value for tb_depart.parent_depart
     *
     * @mbggenerated
     */
    public void setParentDepart(Long parentDepart) {
        this.parentDepart = parentDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.create_time
     *
     * @return the value of tb_depart.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.create_time
     *
     * @param createTime the value for tb_depart.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}