package zzjz.bean;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author 彭鹏
 * @ClassName: Trip
 * @Description: 出差表
 * @date 2017年04月13日11:13
 */
@XmlRootElement
public class TripRequest extends BaseRequest{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.act_id
     *
     * @mbggenerated
     */
    private String actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.e_trip_date
     *
     * @mbggenerated
     */
    private String eTripDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.e_back_date
     *
     * @mbggenerated
     */
    private String eBackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.a_trip_date
     *
     * @mbggenerated
     */
    private String aTripDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.a_back_date
     *
     * @mbggenerated
     */
    private String aBackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.back_time
     *
     * @mbggenerated
     */
    private String backTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.trip_city
     *
     * @mbggenerated
     */
    private String tripCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.trip_day
     *
     * @mbggenerated
     */
    private Double tripDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trip.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.id
     *
     * @return the value of tb_trip.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.id
     *
     * @param id the value for tb_trip.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.act_id
     *
     * @return the value of tb_trip.act_id
     *
     * @mbggenerated
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.act_id
     *
     * @param actId the value for tb_trip.act_id
     *
     * @mbggenerated
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.user_id
     *
     * @return the value of tb_trip.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.user_id
     *
     * @param userId the value for tb_trip.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.user_name
     *
     * @return the value of tb_trip.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.user_name
     *
     * @param userName the value for tb_trip.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.e_trip_date
     *
     * @return the value of tb_trip.e_trip_date
     *
     * @mbggenerated
     */
    public String geteTripDate() {
        return eTripDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.e_trip_date
     *
     * @param eTripDate the value for tb_trip.e_trip_date
     *
     * @mbggenerated
     */
    public void seteTripDate(String eTripDate) {
        this.eTripDate = eTripDate == null ? null : eTripDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.e_back_date
     *
     * @return the value of tb_trip.e_back_date
     *
     * @mbggenerated
     */
    public String geteBackDate() {
        return eBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.e_back_date
     *
     * @param eBackDate the value for tb_trip.e_back_date
     *
     * @mbggenerated
     */
    public void seteBackDate(String eBackDate) {
        this.eBackDate = eBackDate == null ? null : eBackDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.a_trip_date
     *
     * @return the value of tb_trip.a_trip_date
     *
     * @mbggenerated
     */
    public String getaTripDate() {
        return aTripDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.a_trip_date
     *
     * @param aTripDate the value for tb_trip.a_trip_date
     *
     * @mbggenerated
     */
    public void setaTripDate(String aTripDate) {
        this.aTripDate = aTripDate == null ? null : aTripDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.a_back_date
     *
     * @return the value of tb_trip.a_back_date
     *
     * @mbggenerated
     */
    public String getaBackDate() {
        return aBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.a_back_date
     *
     * @param aBackDate the value for tb_trip.a_back_date
     *
     * @mbggenerated
     */
    public void setaBackDate(String aBackDate) {
        this.aBackDate = aBackDate == null ? null : aBackDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.start_time
     *
     * @return the value of tb_trip.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.start_time
     *
     * @param startTime the value for tb_trip.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.back_time
     *
     * @return the value of tb_trip.back_time
     *
     * @mbggenerated
     */
    public String getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.back_time
     *
     * @param backTime the value for tb_trip.back_time
     *
     * @mbggenerated
     */
    public void setBackTime(String backTime) {
        this.backTime = backTime == null ? null : backTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.trip_city
     *
     * @return the value of tb_trip.trip_city
     *
     * @mbggenerated
     */
    public String getTripCity() {
        return tripCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.trip_city
     *
     * @param tripCity the value for tb_trip.trip_city
     *
     * @mbggenerated
     */
    public void setTripCity(String tripCity) {
        this.tripCity = tripCity == null ? null : tripCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.trip_day
     *
     * @return the value of tb_trip.trip_day
     *
     * @mbggenerated
     */
    public Double getTripDay() {
        return tripDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.trip_day
     *
     * @param tripDay the value for tb_trip.trip_day
     *
     * @mbggenerated
     */
    public void setTripDay(Double tripDay) {
        this.tripDay = tripDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trip.create_time
     *
     * @return the value of tb_trip.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trip.create_time
     *
     * @param createTime the value for tb_trip.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}
