package zzjz.bean;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author 彭鹏
 * @ClassName: zoa
 * @Description:
 * @date 2017年04月13日16:18
 */
@XmlRootElement
public class VacationRequest extends BaseRequest{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.act_id
     *
     * @mbggenerated
     */
    private String actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.leave_typ
     *
     * @mbggenerated
     */
    private String leaveTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.leave_date
     *
     * @mbggenerated
     */
    private String leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.back_date
     *
     * @mbggenerated
     */
    private String backDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.leave_part
     *
     * @mbggenerated
     */
    private String leavePart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.back_part
     *
     * @mbggenerated
     */
    private String backPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.leave_day
     *
     * @mbggenerated
     */
    private Double leaveDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_vacation.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.id
     *
     * @return the value of tb_vacation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.id
     *
     * @param id the value for tb_vacation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.act_id
     *
     * @return the value of tb_vacation.act_id
     *
     * @mbggenerated
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.act_id
     *
     * @param actId the value for tb_vacation.act_id
     *
     * @mbggenerated
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.user_id
     *
     * @return the value of tb_vacation.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.user_id
     *
     * @param userId the value for tb_vacation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.user_name
     *
     * @return the value of tb_vacation.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.user_name
     *
     * @param userName the value for tb_vacation.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.leave_typ
     *
     * @return the value of tb_vacation.leave_typ
     *
     * @mbggenerated
     */
    public String getLeaveTyp() {
        return leaveTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.leave_typ
     *
     * @param leaveTyp the value for tb_vacation.leave_typ
     *
     * @mbggenerated
     */
    public void setLeaveTyp(String leaveTyp) {
        this.leaveTyp = leaveTyp == null ? null : leaveTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.reason
     *
     * @return the value of tb_vacation.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.reason
     *
     * @param reason the value for tb_vacation.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.leave_date
     *
     * @return the value of tb_vacation.leave_date
     *
     * @mbggenerated
     */
    public String getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.leave_date
     *
     * @param leaveDate the value for tb_vacation.leave_date
     *
     * @mbggenerated
     */
    public void setLeaveDate(String leaveDate) {
        this.leaveDate = leaveDate == null ? null : leaveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.back_date
     *
     * @return the value of tb_vacation.back_date
     *
     * @mbggenerated
     */
    public String getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.back_date
     *
     * @param backDate the value for tb_vacation.back_date
     *
     * @mbggenerated
     */
    public void setBackDate(String backDate) {
        this.backDate = backDate == null ? null : backDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.leave_part
     *
     * @return the value of tb_vacation.leave_part
     *
     * @mbggenerated
     */
    public String getLeavePart() {
        return leavePart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.leave_part
     *
     * @param leavePart the value for tb_vacation.leave_part
     *
     * @mbggenerated
     */
    public void setLeavePart(String leavePart) {
        this.leavePart = leavePart == null ? null : leavePart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.back_part
     *
     * @return the value of tb_vacation.back_part
     *
     * @mbggenerated
     */
    public String getBackPart() {
        return backPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.back_part
     *
     * @param backPart the value for tb_vacation.back_part
     *
     * @mbggenerated
     */
    public void setBackPart(String backPart) {
        this.backPart = backPart == null ? null : backPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.leave_day
     *
     * @return the value of tb_vacation.leave_day
     *
     * @mbggenerated
     */
    public Double getLeaveDay() {
        return leaveDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.leave_day
     *
     * @param leaveDay the value for tb_vacation.leave_day
     *
     * @mbggenerated
     */
    public void setLeaveDay(Double leaveDay) {
        this.leaveDay = leaveDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.create_time
     *
     * @return the value of tb_vacation.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.create_time
     *
     * @param createTime the value for tb_vacation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vacation.status
     *
     * @return the value of tb_vacation.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vacation.status
     *
     * @param status the value for tb_vacation.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}
